POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEiLCJpZCI6IjYzYTMzMDkyY2FmZDNmZWM4MDIzMWFiYiIsImlhdCI6MTY3MTY0NDI1Mn0.7b0hup_Ti-gZFY1zOY_b51Vo6SG6iMYc8EcLYUquKTU

{
    "content": "erterek",
    "important": true,
}

###

DELETE http://localhost:3001/api/notes/638cfdf8552a4dbd06f92ca9
###

###
PUT http://localhost:3001/api/notes/638cfd7c552a4dbd06f92ca4 HTTP/1.1
content-type: application/json

{
    "content": "Anotha banga",
    "important": true
}